# Generated by Django 5.2.8 on 2025-11-18 04:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('description', models.TextField(blank=True, verbose_name='产品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('category', models.CharField(max_length=100, verbose_name='分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='ProductInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_reviews', models.IntegerField(default=0, verbose_name='总评论数')),
                ('avg_rating', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('sentiment_distribution', models.JSONField(default=dict, verbose_name='情感分布')),
                ('common_topics', models.JSONField(default=list, verbose_name='常见话题')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='review_insights.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品洞察',
                'verbose_name_plural': '产品洞察',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='评论者')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('rating', models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], verbose_name='评分')),
                ('sentiment', models.CharField(choices=[('positive', '正面'), ('negative', '负面'), ('neutral', '中性')], max_length=20, verbose_name='情感倾向')),
                ('confidence', models.FloatField(default=0.0, verbose_name='情感置信度')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review_insights.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_topics', models.JSONField(default=list, verbose_name='关键话题')),
                ('emotion_score', models.JSONField(default=dict, verbose_name='情感分数')),
                ('word_count', models.IntegerField(default=0, verbose_name='词数')),
                ('reading_time', models.IntegerField(default=0, verbose_name='阅读时间(分钟)')),
                ('spam_score', models.FloatField(default=0.0, verbose_name='垃圾评论分数')),
                ('helpful_votes', models.IntegerField(default=0, verbose_name='有用投票')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='review_insights.review', verbose_name='评论')),
            ],
            options={
                'verbose_name': '评论洞察',
                'verbose_name_plural': '评论洞察',
            },
        ),
        migrations.CreateModel(
            name='ReviewTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('review_count', models.IntegerField(default=0, verbose_name='评论数量')),
                ('avg_rating', models.FloatField(default=0.0, verbose_name='平均评分')),
                ('sentiment_score', models.FloatField(default=0.0, verbose_name='情感分数')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='review_insights.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '评论趋势',
                'verbose_name_plural': '评论趋势',
                'ordering': ['-date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
